; ---------------------------
; Hotkey notation reference:
; ^ = Ctrl   ? e.g. ^h means Ctrl + H
; ! = Alt    ? e.g. !h means Alt + H
; + = Shift  ? e.g. +h means Shift + H
; # = Win    ? e.g. #h means Win + H
; ---------------------------

[Hotkeys]

Hack=h
Terminate=t
Reload=r

;27 May 2025: New hotkey
;Use this key if you want to manually select the prints.. Useful when the script selects wrong prints.. Simply press m (or the key you choose) instead of r to go into manual mode..
Manual=m